[project]
name = "netflix-ai-assistant"
version = "0.1.0"
description = "Hybrid AI-powered Netflix movie assistant using filtering and RAG"
authors = [
    { name = "Vivek Macharla" }
]

dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "sentence-transformers",
    "faiss-cpu",
    "ollama"
]